### ISSUE TITLE
Cmd+<

### ISSUE THREAD

**Issue by DutchPete** [argenos/hotkeysplus-obsidian#14]
I am on macOS. When want to use <kbd>Cmd</kbd> + <kbd><</kbd> it opens the Obsidian settings key.
Please explain how this works.

**Comment by jjspace** [comment]
@DutchPete technically you're hitting the shortcut `Cmd+,` which is set to `Open Settings`. You have a couple options here

1. Unbind the "Open Settings" hotkey in settings
2. Rebind the "Hotkeys++: Toggle line to block quote" to something else. If you want the same key I suggest `Cmd+Shift+,` which would essentially mean the same thing because you access the `<` character with `Shift+,`

As a side note @argenos, I'm not sure it's actually possible to directly trigger `Ctrl+<` at all due to the aforementioned fact that it's really `Shift+,` which Obsidian seems to detect differently.

**Comment by argenos** [comment]
This seems to work on Linux alright. For now, the workaround is to remove the default hotkey and assign your own. This might be a good idea anyways, as I'll soon remove the default hotkeys to follow some best practices.

**Comment by DutchPete** [comment]
@jjspace: I opted for 2. and that works. Thanks a lot for you help.

**Comment by OPEN1004MIND** [comment]
I think Cmd+> better than Cmd+< ^^;
